### ISSUE TITLE
webpack: Failed to compile.

### ISSUE THREAD

**Issue by amirensit** [mehmetsunkur/jhipster-ngxadmin#3]
After  generating a jhipster project, i cloned  akveo/ngx-admin from github into the project.
When i run yarn start it shows this error : 

`ERROR in [at-loader] ./src/main/webapp/app/app-routing.module.ts:3:22
    TS2305: Module '"C:/Users/amir/Desktop/jhipster ngxadmin/src/main/webapp/app/layouts/index"' has no exported member 'navbarRoute'.`
`ERROR in [at-loader] ./src/main/webapp/app/ngx-admin/@theme/components/tiny-mce/tiny-mce.component.ts:16:5
    TS2304: Cannot find name 'tinymce'.`
`ERROR in [at-loader] ./src/main/webapp/app/ngx-admin/@theme/components/tiny-mce/tiny-mce.component.ts:31:5
    TS2304: Cannot find name 'tinymce'.
Child html-webpack-plugin for "index.html":
     2 assets
       1 module
webpack: Failed to compile.`

I hope that this issue will not be closed :)

**Comment by amirensit** [comment]
I solved this problem by importing navbarRoute module.
The project works but when i click on any item on the sidebar, it shows errors.

![image](https://user-images.githubusercontent.com/19771879/36485438-84d94e72-171c-11e8-910b-5435863cb274.png)

**Comment by rajatKumar671** [comment]
I have facing problem went using this them in my project can help me

**Comment by rajatKumar671** [comment]
I am facing a problem when using this theme in my project can you help me

**Comment by amirensit** [comment]
I aborded the use of that template and jhipster version is going too much faster.
Sorry I cannot help.
