### ISSUE TITLE
unable to interact with back-end

### ISSUE THREAD

**Issue by amirensit** [mehmetsunkur/jhipster-ngxadmin#4]
With this template, after fixing the problem of webpack, I am unable to see any entity in the dashboard.
There is no interaction with jhipster functionality.

**Comment by elena-enacache1** [comment]
Hello, did you manage to include ngx-admin in jhipster and have a functional app?

**Comment by amirensit** [comment]
I aborded that template with jhipster and I used `bootstrap material design` and `angular material design` instead.
